#pragma once

#include<NativeGameplayTags.h>

namespace SleepyFireGameplayTags {
	SLEEPYFIRE_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that SleepyFire will use
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	SLEEPYFIRE_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	SLEEPYFIRE_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	SLEEPYFIRE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
}
